exclude: README.rst

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ".*"
        exclude: "Archive/|Guitar|Uh|Up|Years/Top Ten/|\\..*"
        args: ["--ignore-case"]
      - id: trailing-whitespace
