exclude: README.rst

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: ".*"
        exclude: "Guitar|Up|Years/Top Ten/|\\..*"
        args: ["--ignore-case", "--unique"]
    -   id: trailing-whitespace
